### ISSUE TITLE
Elasticsearch 跟 MongoDB 無法整合

### ISSUE THREAD

**Issue by LittleWhiteYA** [PPAV-inc/website#16]
開個 issue 紀錄一下

目前遇到實作上的困難點在於
Elasticsearch 主要是做文字搜尋引擎
因此在所有資料進 ES 之前會對每個欄位做 "前處理"
https://www.elastic.co/guide/cn/elasticsearch/guide/current/mapping-intro.html
E.g.
https://stackoverflow.com/questions/39582457/elasticsearch-match-any-possible-exact-value-of-an-array-in-an-array

針對這點，如果要在 query 出來的結果做一層 filter
ES 我覺得不是很好的工具
相較之下 MongoDB 就能很容易做到

目前還沒找到 ES 要如何做到這點，以及做到這點速度上是否優於 MongoDB
因此我覺得現在就維持 2 種 DB 如何？

@xxhomey19

**Comment by xxhomey19** [comment]
我查了一下 ES 有 [bool query](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/query-dsl-bool-query.html) 也有 [range query](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/query-dsl-range-query.html)
這些沒辦法做出 filter 的效果嗎？

**Comment by LittleWhiteYA** [comment]
沒有辦法，因為在資料進 ES 之前，原本是存 array 的資料，E.g. 有哪些女優，預設就會自動被打散
我猜這應該也是為何 ES 文本搜尋可以這麼強

**Comment by LittleWhiteYA** [comment]
這個暫時決定分成 2 個 DB
